spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/promotion?allowMultiQueries=true&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 123456
    initial-size: 10
    max-active: 100
    min-idle: 10
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
    filter:
      stat:
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # config-location: classpath:mybatis-config.xml
  type-aliases-package: com.coolshop.promotion.model
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    use-column-label: true
    map-underscore-to-camel-case: true