spring:
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/coolshop?allowMultiQueries=true&amp;useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # config-location: classpath:mybatis-config.xml
  type-aliases-package: com.coolshop.ucenter.model
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    use-column-label: true
    map-underscore-to-camel-case: true